- name: Provision systems
  hosts: localhost
  connection: local
  vars:
    turn_name: turn-host
    workadventure_name: workadventure-host
  tasks:

    - name: Check for SSH key
      register: key_info
      hetzner.hcloud.hcloud_ssh_key_info:
        name: Workadventure SSH
        api_token: "{{hetzner_token}}"

    - name: Manage the SSH key
      when: (key_info.hcloud_ssh_key_info | length == 0) or state == "absent"
      hetzner.hcloud.hcloud_ssh_key:
        name: Workadventure SSH
        public_key: "{{ lookup('file', public_key) }}"
        api_token: "{{hetzner_token}}"
        state: "{{state}}"

    - name: Check for turn host
      hcloud_server_info:
        name: "{{turn_name}}"
        api_token: "{{hetzner_token}}"
      register: turn_info

    - name: Print turn host attributes  
      when: turn_info.hcloud_server_info | length > 0
      ansible.builtin.debug:
        msg: "{{turn_info.hcloud_server_info}}"

    - name: Manage turn host
      when: (turn_info.hcloud_server_info | length == 0) or state == "absent"
      register: turn_result
      hetzner.hcloud.hcloud_server:
        name: "{{turn_name}}"
        server_type: cx21
        image: ubuntu-22.04
        location: nbg1
        ssh_keys:
          - Workadventure SSH
        api_token: "{{hetzner_token}}"
        state: "{{state}}"

    - name: Print turn creation results  
      when: state == "present" and turn_result.hcloud_server is defined and (turn_result.hcloud_server | length > 0)
      ansible.builtin.debug:
        msg: "{{turn_result.hcloud_server}}"
   

    - name: Check for workadventure host
      hcloud_server_info:
        name: "{{workadventure_name}}"
        api_token: "{{hetzner_token}}"
      register: workadventure_info

    - name: Print workadventure host attributes  
      when: workadventure_info.hcloud_server_info | length > 0
      ansible.builtin.debug:
        msg: "{{workadventure_info.hcloud_server_info}}"

    - name: Manage workadventure host
      when: (workadventure_info.hcloud_server_info | length == 0)  or state == "absent"
      register: workadventure_result
      hetzner.hcloud.hcloud_server:
        name: "{{workadventure_name}}"
        server_type: cx21
        image: ubuntu-22.04
        location: nbg1
        ssh_keys:
          - Workadventure SSH
        api_token: "{{hetzner_token}}"
        state: "{{state}}"

    - name: Print workadventure creation results  
      when: state == "present" and workadventure_result.hcloud_server is defined and (workadventure_result.hcloud_server | length > 0)
      ansible.builtin.debug:
        msg: "{{workadventure_result.hcloud_server}}"

    - name: Print IP hint
      when: state == "present"
      ansible.builtin.debug:
        msg: Take a look at the host attributes above and insert the IPs into you DNS and the .env places.

    - name: Print deletion hint
      when: state == "absent"
      ansible.builtin.debug:
        msg: The host and SSH keys are removed.