- name: Provision systems
  hosts: localhost
  connection: local
  tasks:

    - name: Check for SSH key
      register: key_info
      hetzner.hcloud.hcloud_ssh_key_info:
        name: Workadventure SSH
        api_token: "{{hetzner_token}}"

    - name: Manage the SSH key
      when: (key_info.hcloud_ssh_key_info | length == 0) or state == "absent"
      hetzner.hcloud.hcloud_ssh_key:
        name: Workadventure SSH
        public_key: "{{ lookup('file', public_key) }}"
        api_token: "{{hetzner_token}}"
        state: "{{state}}"

    - name: Setup machines
      ansible.builtin.include_tasks: tasks/setup-hosts.tasks.yaml
      loop:
        - name: turn
          server_type: cx21
          location: nbg1
          ssh_keys:
            - Workadventure SSH
        - name: workadventure
          server_type: cx21
          location: nbg1
          ssh_keys:
            - Workadventure SSH

    - name: Print IP hint
      when: state == "present"
      ansible.builtin.debug:
        msg: Take a look at the host attributes above and insert the IPs into you DNS and the .env places.

    - name: Print deletion hint
      when: state == "absent"
      ansible.builtin.debug:
        msg: The host and SSH keys are removed.