---
roles:
  - name: geerlingguy.docker
    version: 5.2.1
  - name: geerlingguy.pip
    version: 2.2.0

collections:
  - name: community.docker
    version: 2.7.1
    source: https://galaxy.ansible.com


