- name: Turn system
  hosts: turn
  tasks:
    - name: Ensure colors
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        regexp: '^export PS1='
        line: 'export PS1="\[\e[32m\][\[\e[m\]\[\e[31m\]\u\[\e[m\]\[\e[33m\]@\[\e[m\]\[\e[32m\]\h\[\e[m\]:\[\e[36m\]\w\[\e[m\]\[\e[32m\]]\[\e[m\]\[\e[32;47m\]\\$\[\e[m\] "'
        create: true

    - name: Ensure docker environment
      become: true
      vars:
        docker_install_compose_plugin: true
        docker_service_enabled: true
        docker_users: "root"
        docker_service_manage: true
        docker_restart_handler_state: reloaded
      ansible.builtin.import_role:
        name: geerlingguy.docker

    - name: Ensure docker python environment
      become: true
      vars:
        pip_install_packages:
          - docker
          - docker-compose
          - pyaml
      ansible.builtin.import_role:
        name: geerlingguy.pip
    
    - name: Reset ssh connection to get new group membership
      ansible.builtin.meta: reset_connection

    - name: Ensure turn folder
      ansible.builtin.file:
        path: ~/turn
        state: directory

    - name: Transfer relevant files
      loop:
        - src: ../docker-compose.turn.yaml
          dest: docker-compose.yaml
        - src: ../.env
          dest: .env
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "~/turn/{{ item.dest }}"
      
    - name: Start Turn docker-compose
      community.docker.docker_compose:
        project_src: ~/turn

- name: Workadventure system
  hosts: workadventure
  tasks:
    - name: Ensure colors
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        regexp: '^export PS1='
        line: 'export PS1="\[\e[32m\][\[\e[m\]\[\e[31m\]\u\[\e[m\]\[\e[33m\]@\[\e[m\]\[\e[32m\]\h\[\e[m\]:\[\e[36m\]\w\[\e[m\]\[\e[32m\]]\[\e[m\]\[\e[32;47m\]\\$\[\e[m\] "'
        create: true

    - name: Ensure docker environment
      become: true
      vars:
        docker_install_compose_plugin: true
        docker_service_enabled: true
        docker_users: "root"
        docker_service_manage: true
        docker_restart_handler_state: reloaded
      ansible.builtin.import_role:
        name: geerlingguy.docker

    - name: Ensure docker python environment
      become: true
      vars:
        pip_install_packages:
          - docker
          - docker-compose
          - pyaml
      ansible.builtin.import_role:
        name: geerlingguy.pip
    
    - name: Reset ssh connection to get new group membership
      ansible.builtin.meta: reset_connection

    - name: Ensure workadventure folder
      ansible.builtin.file:
        path: ~/workadventure
        state: directory

    - name: Transfer relevant files
      register: transfer_result
      loop:
        - src: ../docker-compose.yaml
          dest: docker-compose.yaml
        - src: ../.env
          dest: .env
        - src: ../ejabberd.template.yaml
          dest: ejabberd.template.yaml
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "~/workadventure/{{ item.dest }}"
      
    - name: Start Workadventure docker-compose
      register: docker_status
      community.docker.docker_compose:
        project_src: ~/workadventure

    - name: Restart ejabberd if necessary
      when: "(transfer_result.results | selectattr('dest', 'search', 'ejabberd.template.yaml$') | first).changed and not docker_status.changed"
      community.docker.docker_compose:
        project_src: ~/workadventure
        restarted: true
        services:
          - ejabberd