- name: Basic systems
  hosts: all
  tasks:
    - name: Update package sources
      ansible.builtin.apt:
        update_cache: yes

    - name: Ensure fancy environment
      become: true
      vars:
        oh_my_zsh_install: yes
        oh_my_zsh_theme: agnoster
        oh_my_zsh_plugins:
          - gitfast
          - pip
          - python
          - thefuck
          - docker
          - docker-compose
          - shrink-path
        oh_my_zsh_dependencies:
          - git
          - zsh
          - python3
          - python3-pip
        users:
          - username: "{{ ansible_user_id }}"
      ansible.builtin.import_role:
        name: gantsign.oh-my-zsh
      
    - name: Ensure shrink path
      ansible.builtin.lineinfile:
        path: ~"{{ ansible_user_id }}"/.zshrc
        regexp: '^prompt_dir'
        line: 'prompt_dir () { prompt_segment blue black "$(shrink_path -f)" }'
        create: true

    - name: Ensure pip packages
      become: true
      vars:
        pip_install_packages:
          - thefuck
      ansible.builtin.import_role:
        name: geerlingguy.pip

    - name: Ensure docker environment
      become: true
      vars:
        docker_install_compose_plugin: true
        docker_service_enabled: true
        docker_users: "{{ ansible_user_id }}"
        docker_service_manage: true
        docker_restart_handler_state: reloaded
      ansible.builtin.import_role:
        name: geerlingguy.docker

    - name: Ensure docker python environment
      become: true
      vars:
        pip_install_packages:
          - docker
          - docker-compose
          - pyaml
      ansible.builtin.import_role:
        name: geerlingguy.pip
    
    - name: Reset ssh connection to get new group membership
      ansible.builtin.meta: reset_connection

- name: Turn system
  hosts: turn
  tasks:
    - name: Ensure turn folder
      ansible.builtin.file:
        path: ~/turn
        state: directory

    - name: Transfer relevant files
      loop:
        - src: ../docker-compose.turn.yaml
          dest: docker-compose.yaml
        - src: ../.env
          dest: .env
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "~/turn/{{ item.dest }}"
      
    - name: Start Turn docker-compose
      community.docker.docker_compose:
        project_src: ~/turn

- name: Workadventure system
  hosts: workadventure
  tasks:
    - name: Ensure workadventure folder
      ansible.builtin.file:
        path: ~/workadventure
        state: directory

    - name: Transfer relevant files
      register: transfer_result
      loop:
        - src: ../docker-compose.yaml
          dest: docker-compose.yaml
        - src: ../.env
          dest: .env
        - src: ../ejabberd.template.yaml
          dest: ejabberd.template.yaml
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "~/workadventure/{{ item.dest }}"
      
    - name: Start Workadventure docker-compose
      register: docker_status
      community.docker.docker_compose:
        project_src: ~/workadventure

    - name: Restart ejabberd if necessary
      when: "(transfer_result.results | selectattr('dest', 'search', 'ejabberd.template.yaml$') | first).changed and not docker_status.changed"
      community.docker.docker_compose:
        project_src: ~/workadventure
        restarted: true
        services:
          - ejabberd